package fxapps.test_jpa_wih;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Product implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRODUCT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PRODUCT_ID_SEQ", name = "PRODUCT_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label(value = "price")
   private java.lang.Float price;

   public Product()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Float getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Float price)
   {
      this.price = price;
   }

   public Product(java.lang.Long id, java.lang.String name,
         java.lang.Float price)
   {
      this.id = id;
      this.name = name;
      this.price = price;
   }
   
   public String toString() {
       return "[name=" + this.name + ", price=" + this.price + "]";
   }

}